### PR TITLE
Install and replace the default wallpaper

### PR DESCRIPTION
**Pull request by naruxde**
This change sticks to the old method of how we install our default background. New here is the beautiful name of our background and that we put a link on the default system background.

See README.Debian

### CODE REVIEW

**Comment by RamiGspo** [comment]
It seems to be all right... BUT the control file is not in the same order as in our last repositories.

It should be something like that:

```
Source: revpi-wallpaper
Section: contrib/electronics
Priority: optional
Maintainer: KUNBUS GmbH <support@kunbus.com>
Rules-Requires-Root: no
Homepage: https://revolutionpi.com/
Vcs-Browser: https://github.com/RevolutionPi/revpi-wallpaper
Vcs-Git: https://github.com/RevolutionPi/revpi-wallpaper.git -b raspios/bullseye
```

@naruxde It is posible to change it? ;-)

**Comment by RamiGspo** [comment]
And [this commit](https://github.com/RevolutionPi/revpi-wallpaper/pull/6/commits/6c6482a341652fdcb9bb0f41a6ee86c107f75d97) is for me toooo long.... It's a really complicated title and I don't have a better one right now :-(

**Comment by naruxde** [comment]
> And [this commit](https://github.com/RevolutionPi/revpi-wallpaper/pull/6/commits/6c6482a341652fdcb9bb0f41a6ee86c107f75d97) is for me toooo long.... It's a really complicated title and I don't have a better one right now :-(

I split the content to two commits.

**Review by nbuchwitz — CHANGES_REQUESTED** [review]
Personally I dislike file names with spaces (weird auto-completion, needs escaping, etc.). How about `revolution_pi.jpg`

**Comment by naruxde** [comment]
> Personally I dislike file names with spaces (weird auto-completion, needs escaping, etc.). How about `revolution_pi.jpg`

No way 🤣 This is where we are moving on the GUI. It's about beauty and aesthetics. In addition, there is our definition of proper names and they must also be adhered to. This is the reason why the blank space was deliberately installed here.

**Review by nbuchwitz — APPROVED** [review]

**Pull request merged**
